DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS menus;

CREATE TABLE restaurants(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
);

CREATE TABLE menus (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  length TEXT NOT NULL,
  type TEXT NOT NULL,
  menu_id BIGINT REFERENCES restaurants(id)
);
